### ISSUE TITLE
R/R Studio version warning: Setp0_Global_SetUp

### ISSUE THREAD

**Issue by willemijnvroege** [PSU-AXA-Somalia/AXA-PSU-Somalia#2]
Hi Helen, 

I would suggest to move the warnings around the version numbers (lines 227:232 of Setp0_Global_SetUp) to the beginning of that code: With an older R version, the code now interrupts before it reaches the warning. (it stops when it should install/update the packages).

Btw: I run on version 4.0.2 and installing the packages doesn't work, so maybe you want to create a warning also for versions smaller than 4.1

Btw: I could push suggested changes to a fork where you can decide which to merge or not merge with the main code. Please let me know if I should do that.

**Comment by hgreatrex** [comment]
Hello!
This should run on R 4.0.2 (It's run for me on 4.0.5).   -  I thought that you couldn't install the packages because you didn't have admin permission to do so?

I've moved the warnings around at least.

And I'm happy for you to push changes to a fork!

**Comment by hgreatrex** [comment]
Changes pushed, closing here - but it might be good for you to run this live on a call
