### ISSUE TITLE
Directory seperator on Windows

### ISSUE THREAD

**Issue by willemijnvroege** [PSU-AXA-Somalia/AXA-PSU-Somalia#3]
Hi Helen, 

I could image line 41-49 could not be entirely clear for a beginner user. Maybe you write in text something like, "if you use windows, select /" if mac .... 
Have you tested using Sys.info()["sysname"] to define what separator should be used to omit that the user has to select this?

**Comment by hgreatrex** [comment]
This would be an interesting one - I actually had that before and removed it as you had mentioned that windows might be switching to the "/" and I wanted to test.

Great idea on automation
This is what I see for systemname - would you be able to show a windows one, and then yep, this could be automate
<img width="726" alt="Screen Shot 2021-11-19 at 8 08 17 AM" src="https://user-images.githubusercontent.com/5038576/142627957-64dcbc22-7a0c-44c7-81b2-2cc753e6a044.png">

**Comment by hgreatrex** [comment]
Let's debug this one together on the call.  I still don't have access to a
windows machine, so I would like to see what you see - as I think I'm
misunderstanding how the separator works in Windows R..

H


Dr Helen Greatrex (pronouns: she/hers)
Assistant Professor in Remote Sensing and Geospatial Analysis
Department of Geography, Department of Statistics & Co-Hire of the
Institute for Computational and Data Sciences
201 Walker Building
University Park, PA 16802




*Learn more about the Rainbow Science Lab I lead here
<https://science.psu.edu/diversity-initiatives/rainbow-science-network>See
our acknowledgment of the lands Penn State stands on here:
<http://equity.psu.edu/acknowledgement-of-land>*

**Comment by hgreatrex** [comment]
OK, this has now been made full automatic.

You no longer need to enter a dir_main at all as long as you are running your project file
