### ISSUE TITLE
Reading csv

### ISSUE THREAD

**Issue by willemijnvroege** [PSU-AXA-Somalia/AXA-PSU-Somalia#4]
Helen, 

I never had this before, but when I read your csv the first colname is "i...Family" so your code breaks. Maybe it is a language tough my pc does speak english. Not sure, but it could be possible that your code gets more stable if you fill a first colname with a "dataset number" or some unnecessary variable

**Comment by hgreatrex** [comment]
Ahhh...  this is a windows/mac/github thing.
Mac invisible characters are showing up.
Let's do it together in person
H
Dr Helen Greatrex (pronouns: she/hers)
Assistant Professor in Remote Sensing and Geospatial Analysis
Department of Geography, Department of Statistics & Co-Hire of the
Institute for Computational and Data Sciences
201 Walker Building
University Park, PA 16802




*Learn more about the Rainbow Science Lab I lead here
<https://science.psu.edu/diversity-initiatives/rainbow-science-network>See
our acknowledgment of the lands Penn State stands on here:
<http://equity.psu.edu/acknowledgement-of-land>*

**Comment by hgreatrex** [comment]
We fixed this with your wonderful idea of a dummy column
